version: "3.9"

services:
  cyna-auth:
    image: registry.gitlab.com/cyna-project/cyna-auth:latest
    container_name: cyna-auth
    ports:
      - "3000:3000"
    env_file:
      - ./cyna-auth/.env
    depends_on:
      - postgres-auth

  cyna-product:
    image: registry.gitlab.com/cyna-project/cyna-product:latest
    container_name: cyna-product
    ports:
      - "5000:5000"
    env_file:
      - ./cyna-product/.env
    depends_on:
      - postgres-product

  cyna-billing:
    image: registry.gitlab.com/cyna-project/cyna-billing:latest
    container_name: cyna-billing
    ports:
      - "4000:4000"
    env_file:
      - ./cyna-billing/.env
    depends_on:
      - postgres-billing

  postgres-auth:
    image: postgres:15
    container_name: postgres-auth
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cyna_auth
    ports:
      - "5433:5432"
    volumes:
      - pgdata-auth:/var/lib/postgresql/data

  postgres-product:
    image: postgres:15
    container_name: postgres-product
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cyna_product
    ports:
      - "5434:5433"
    volumes:
      - pgdata-product:/var/lib/postgresql/data

volumes:
  pgdata-auth:
  pgdata-product:
